version: 2
updates:
- package-ecosystem: gomod
  directory: "/provider"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  reviewers:
  - jaxxstorm
  labels:
  - dependencies
  - dependabot
- package-ecosystem: gomod
  directory: "/sdk"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  reviewers:
  - jaxxstorm
  labels:
  - dependencies
  - dependabot
