name: release
on:
  pull_request:
    branches:
      - master
  push:
    tags: [ "v*" ]

env:
  ORG: jaxxstorm

jobs:
  nodejs:
    runs-on: ubuntu-latest
    needs: provider
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.13.10
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.10'
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider ORG=jaxxstorm
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build SDK
        run: make build_node ORG=jaxxstorm
      - name: Publish to NPM
        run: yarn --cwd sdk/nodejs/bin publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  python:
    runs-on: ubuntu-latest
    needs: provider
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.13.10
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.10'
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider ORG=jaxxstorm
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build SDK
        run: make build_python ORG=jaxxstorm
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: sdk/python/bin/dist/
  dotnet:
    runs-on: ubuntu-latest
    needs: provider
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.13.10
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.10'
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider ORG=jaxxstorm
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.201'
      - name: Build SDK
        run: make build_dotnet ORG=jaxxstorm
      - name: Publish nuget
        run: ./scripts/publish-nuget-package.sh .
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  provider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.13.10
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.10'
      - name: Ensure dependencies
        run: make ensure
      - name: Generate provider deps
        run: make provider ORG=jaxxstorm
      - if: github.event_name == 'pull_request'
        name: Goreleaser snapshot
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.129.0
          args: release --rm-dist --snapshot
      - if: startsWith(github.event.push.tags, 'v')
        name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.129.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


