env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate provider for Dependabot
on:
  pull_request:
    types: [ labeled ]

jobs:
  generate:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: pulumi/pulumictl
    - name: Install golang-ci
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: golangci/golangci-lint
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.1.1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 13.x
        registry-url: https://registry.npmjs.org
    - name: Setup DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.301
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15.x
    - name: Generate
      run: |
        make install_plugins provider build_sdks
    - uses: EndBug/add-and-commit@v9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

